/**
 * Avatar utility — returns human face images from the Human Faces Dataset
 * stored in /public/avatars/Human Faces Dataset/
 *
 * Gender-aware: matches female faces to female names and male faces to male names.
 * Uses gender_manifest.json (generated by classify_genders.py) for accurate matching.
 * Falls back to index-based split (odd=male, even=female) if manifest is absent.
 *
 * Dan's profile pic lives in /public/my-avatar/profile.jpg
 */

// ─── Constants ─────────────────────────────────────────────────────────────

const REAL_BASE = '/avatars/Human Faces Dataset/Real Images/';
const AI_BASE = '/avatars/Human Faces Dataset/AI-Generated Images/';

// How many images are in each folder (used as fallback when manifest not loaded)
const REAL_COUNT = 5000;
const AI_COUNT = 4630;

// ─── Gender manifest (loaded lazily at runtime) ─────────────────────────────

interface GenderManifest {
    real: { male: string[]; female: string[] };
    ai: { male: string[]; female: string[] };
}

let _manifest: GenderManifest | null = null;
let _manifestLoading = false;
let _manifestCallbacks: Array<() => void> = [];

async function loadManifest(): Promise<GenderManifest | null> {
    if (_manifest) return _manifest;
    if (_manifestLoading) {
        return new Promise(resolve => {
            _manifestCallbacks.push(() => resolve(_manifest));
        });
    }
    _manifestLoading = true;
    try {
        const res = await fetch('/avatars/gender_manifest.json');
        if (!res.ok) throw new Error('not found');
        _manifest = await res.json();
        _manifestCallbacks.forEach(cb => cb());
        return _manifest;
    } catch {
        _manifestCallbacks.forEach(cb => cb());
        return null;
    }
}

// ─── Name-based gender detection ──────────────────────────────────────────

const FEMALE_NAMES = new Set([
    'amanda', 'amy', 'angela', 'anna', 'ashley', 'barbara', 'betty', 'brenda', 'carol', 'catherine',
    'cynthia', 'debra', 'diane', 'dorothy', 'emily', 'helen', 'jennifer', 'jessica', 'karen', 'kathleen',
    'laura', 'linda', 'lisa', 'maria', 'mary', 'melissa', 'michelle', 'patricia', 'rachel', 'rebecca',
    'ruth', 'sandra', 'sarah', 'sharon', 'shirley', 'stephanie', 'tamara', 'virginia', 'brittany', 'heather',
    'megan', 'tiffany', 'amber', 'ashley', 'samantha', 'taylor', 'madison', 'emma', 'olivia', 'sophia',
    'isabella', 'ava', 'mia', 'charlotte', 'abigail', 'harper', 'ella', 'evelyn', 'camila', 'luna',
    'penelope', 'scarlett', 'victoria', 'grace', 'chloe', 'riley', 'zoey', 'nora', 'lily', 'eleanor',
    'hannah', 'lillian', 'addison', 'aubrey', 'natalie', 'zoe', 'leah', 'hazel', 'violet', 'aurora',
    'savannah', 'audrey', 'brooklyn', 'bella', 'claire', 'skylar', 'lucy', 'paisley', 'everly', 'anna',
    'caroline', 'nova', 'genesis', 'emilia', 'kennedy', 'samantha', 'maya', 'willow', 'kinsley', 'naomi',
    'aaliyah', 'elena', 'kate', 'allison', 'alexa', 'ariana', 'layla', 'julia', 'destiny', 'jasmine',
    'diana', 'nicole', 'stephanie', 'andrea', 'tanya', 'cassandra', 'brittney', 'kristin', 'dawn', 'crystal',
]);

const MALE_NAMES = new Set([
    'andrew', 'anthony', 'brian', 'charles', 'christopher', 'daniel', 'david', 'donald', 'edward', 'eric',
    'frank', 'gary', 'george', 'gregory', 'jack', 'jacob', 'james', 'jason', 'jeffrey', 'john',
    'jonathan', 'joshua', 'justin', 'kenneth', 'kevin', 'lawrence', 'mark', 'matthew', 'michael', 'nicholas',
    'paul', 'raymond', 'richard', 'robert', 'ronald', 'ryan', 'samuel', 'scott', 'steven', 'thomas',
    'timothy', 'william', 'brandon', 'christopher', 'adam', 'alexander', 'benjamin', 'caleb', 'christian',
    'dylan', 'ethan', 'gabriel', 'henry', 'ian', 'jackson', 'kevin', 'landon', 'liam', 'logan',
    'lucas', 'mason', 'matthew', 'nathan', 'noah', 'oliver', 'owen', 'ryan', 'sebastian', 'tyler',
    'wyatt', 'xavier', 'zachary', 'aaron', 'alex', 'austin', 'blake', 'cameron', 'carlos', 'chad',
    'chase', 'christopher', 'cody', 'cole', 'connor', 'derek', 'devin', 'drake', 'dylan', 'even',
    'gavin', 'hunter', 'jake', 'jared', 'jarrett', 'jaxon', 'jaylen', 'jordan', 'jose', 'julian',
    'justin', 'kyle', 'lance', 'leo', 'marcus', 'miles', 'mitchell', 'nathaniel', 'oscar', 'parker',
    'patrick', 'peter', 'phillip', 'quentin', 'raymond', 'reed', 'ricky', 'ross', 'rubin', 'sean',
    'seth', 'shane', 'simon', 'spencer', 'stephen', 'terry', 'toby', 'trent', 'trevor', 'troy',
    'tucker', 'victor', 'vincent', 'wade', 'warren', 'wayne', 'wesley', 'edward', 'elliot', 'evan',
]);

export function guessGender(name: string): 'male' | 'female' | 'unknown' {
    const first = name.trim().split(/\s+/)[0].toLowerCase();
    if (FEMALE_NAMES.has(first)) return 'female';
    if (MALE_NAMES.has(first)) return 'male';
    return 'unknown';
}

// ─── Hash utility ─────────────────────────────────────────────────────────

function hashCode(str: string): number {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
        hash = (Math.imul(31, hash) + str.charCodeAt(i)) | 0;
    }
    return Math.abs(hash);
}

// ─── Fallback (no manifest) — index-based gender split ────────────────────

function fallbackAvatar(seed: string, gender: 'male' | 'female' | 'unknown'): string {
    // Split by parity: even numbered files ≈ female, odd ≈ male (rough approximation)
    const pad = (n: number) => String(n).padStart(6, '0');
    if (gender === 'female') {
        const idx = (hashCode(seed) % Math.floor(REAL_COUNT / 2)) * 2 + 2; // even
        return `${REAL_BASE}${pad(Math.min(idx, REAL_COUNT))}.jpg`;
    } else {
        const idx = (hashCode(seed) % Math.floor(REAL_COUNT / 2)) * 2 + 1; // odd
        return `${REAL_BASE}${pad(Math.min(idx, REAL_COUNT))}.jpg`;
    }
}

// ─── Public API ────────────────────────────────────────────────────────────

/**
 * Get an avatar URL matched to the gender of the given name.
 * Async — uses the manifest for accuracy, falls back to parity split.
 */
export async function getGenderedAvatar(name: string): Promise<string> {
    const gender = guessGender(name);
    const manifest = await loadManifest();

    if (manifest) {
        const pool = gender === 'female'
            ? [...manifest.real.female, ...manifest.ai.female]
            : [...manifest.real.male, ...manifest.ai.male];

        if (pool.length > 0) {
            const idx = hashCode(name) % pool.length;
            const fname = pool[idx];
            // Determine which base path to use
            const base = manifest.real.male.includes(fname) || manifest.real.female.includes(fname)
                ? REAL_BASE
                : AI_BASE;
            return `${base}${fname}`;
        }
    }

    return fallbackAvatar(name, gender);
}

/**
 * Synchronous version — uses fallback only (no manifest).
 * Use this when you can't await.
 */
export function getSeededAvatar(seed: string): string {
    const gender = guessGender(seed);
    return fallbackAvatar(seed, gender);
}

/**
 * Pick a random avatar from the full Real Images pool.
 */
export function getRandomAvatar(): string {
    const idx = Math.floor(Math.random() * REAL_COUNT) + 1;
    return `${REAL_BASE}${String(idx).padStart(6, '0')}.jpg`;
}

/**
 * Get N unique random avatars.
 */
export function getRandomAvatars(count: number): string[] {
    const indices = new Set<number>();
    while (indices.size < Math.min(count, REAL_COUNT)) {
        indices.add(Math.floor(Math.random() * REAL_COUNT) + 1);
    }
    return Array.from(indices).map(i => `${REAL_BASE}${String(i).padStart(6, '0')}.jpg`);
}

/** Dan's own profile picture. */
export const MY_AVATAR = '/my-avatar/profile.jpg';
